/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4AjY6hfxvIR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function portfolio() {
  return (
    <div className="container max-w-6xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">My NFT Portfolio</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Cosmic Dancer</h2>
            <p className="text-muted-foreground">by John Doe</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Neon Odyssey</h2>
            <p className="text-muted-foreground">by Jane Smith</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Pixel Dreamscape</h2>
            <p className="text-muted-foreground">by Michael Johnson</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Chromatic Fusion</h2>
            <p className="text-muted-foreground">by Emily Williams</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Ethereal Bloom</h2>
            <p className="text-muted-foreground">by David Lee</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Prismatic Mirage</h2>
            <p className="text-muted-foreground">by Sarah Chen</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Quantum Flux</h2>
            <p className="text-muted-foreground">by Alex Gonzalez</p>
          </div>
        </div>
        <div className="bg-background rounded-lg overflow-hidden shadow-lg">
          <img
            src="/placeholder.svg"
            alt="NFT Art"
            width={300}
            height={300}
            className="w-full h-[300px] object-cover"
          />
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Celestial Whispers</h2>
            <p className="text-muted-foreground">by Olivia Hernandez</p>
          </div>
        </div>
      </div>
    </div>
  )
}
